dbuilder-namespace-mapping:
  docker.io: seznam

packages:
  multiarch/debian-debootstrap:
    name: debian
    templates:
      - {file: apt_based.dockerfile, tags: [wheezy], archs: [i386, amd64, armhf]}
      - {file: apt_based.dockerfile, tags: [jessie, stretch], archs: [i386, amd64, armhf, arm64]}

  multiarch/ubuntu-debootstrap:
    name: ubuntu
    templates:
      - {file: ubuntu.dockerfile, tags: [xenial], archs: [i386, amd64, armhf, arm64]}
